name: TipTester
on:
  schedule: 
  - cron: "0 0 * * *"  # schedule tipping to your preference https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events


jobs:
  TipTester:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: tellor-io/tipper@master
      with:
        network: #choose between "rinkeby" and "mainnet"
        requestID: #more info at https://www.tellorscan.com/prices
        dataFreshness: #str: the longest duration of time (ex. 1 day, 2 weeks, etc)
                       #you would wait before requesting new on-chain data
      env:
        # These secrets will need to be manually added to your repo's secrets on github
        # Please make sure that the github secret names match their names here.
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }} # your account's public key
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }} # your account's private key
        MAINNET_NODE: ${{ secrets.MAINNET_NODE }} #your JSON-RPC mainnet endpoint.
        RINKEBY_NODE: ${{ secrets.RINKEBY_NODE }} #your JSON-RPC rinkeby endpoint.